'use client'

import { ReactNode } from 'react'
import { queryClient } from '@/lib/use-query'
import { QueryClientProvider } from '@tanstack/react-query'
import { Nunito } from 'next/font/google'

import './globals.css'

const nunito = Nunito({ variable: '--nunito-font', subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en" className={nunito.variable}>
        <body className="w-full h-screen bg-[#F15156]">{children}</body>
      </html>
    </QueryClientProvider>
  )
}
